library(meffonym)

## save methylation dataset
if (!file.exists("GSE145254-meth.csv"))
    source("save-GSE145254.r")

# load the example dataset generated by save-GSE145254.r
library(data.table)
data <- list(
    dnam=as.matrix(fread("GSE145254-meth.csv"),rownames=1),
    samples=as.data.frame(fread("GSE145254-samples.csv")))

str(data)
# List of 2
#  $ dnam   : num [1:866092, 1:23] 0.652 0.92 0.916 0.96 0.965 ...
#   ..- attr(*, "dimnames")=List of 2
#   .. ..$ : chr [1:866092] "cg00000029" "cg00000103" "cg00000109" "cg00000155" ...
#   .. ..$ : chr [1:23] "GSM4310213" "GSM4310214" "GSM4310215" "GSM4310216" ...
#  $ samples:'data.frame':        23 obs. of  7 variables:
#   ..$ Basename : chr [1:23] "201501980023_R01C01" "201501980036_R01C01" "201501970005_R01C01" "201501980023_R02C01" ...
#   ..$ id       : chr [1:23] "GSM4310213" "GSM4310214" "GSM4310215" "GSM4310216" ...
#   ..$ Female   : int [1:23] 1 1 0 1 1 1 1 0 0 1 ...
#   ..$ status   : chr [1:23] "healthy control" "psychiatric case" "healthy control" "healthy control" ...
#   ..$ Age      : int [1:23] 80 60 53 71 69 61 74 52 75 67 ...
#   ..$ ethnicity: chr [1:23] "Black" "Black" "White" "White" ...
#   ..$ Tissue   : chr [1:23] "Whole Blood" "Whole Blood" "Whole Blood" "Whole Blood" ...

# check samples match 
identical(data$samples$id, colnames(data$dnam))

## ---- -------------------------------------------------------------
ying.raw <- as.data.frame(fread("inst/ying/YingCausAge.csv"))

ying <- ying.raw |> subset(pred.var != "intercept")

intercept <- ying.raw$coef[which(ying.raw$pred.var == "intercept")]
intercept
# [1] 86.80816

# mannually add model to meffonym
meffonym.add.model(
    name = "newCausAge",
    variables = ying$pred.var,
    coefficients = ying$coef,
    description = "test",
    intercept = intercept)

mods <- c("newCausAge", "YingCausAge")

models <- sapply(mods, function(i) {
            meffonym.get.model(i)
        }, simplify=F)
## ---- -------------------------------------------------------------
ret <- sapply(mods, function(i) {
            meffonym.score(data$dnam, i)
        }, simplify=F)

all.equal(ret$newCausAge$score, ret$YingCausAge$score)
identical(ret$newCausAge$score, ret$YingCausAge$score)





